server:
  port: 8090
spring:
  application:
    name: "start-spring-boot-reactor"
  data:
    mongodb:
      uri: mongodb://localhost:27017/${spring.application.name}
config:
  uploads:
    path: C://Users//sergio.barrios//Documents//Proyectos//Image//Web//Reactive//